version: '3.2'

services:
  frontend-sia:
     build: .
     restart: always
     volumes:
       - ./:/usr/src/app
     ports:
       - 80:8080
     env_file:
       - .env
     command: npm run serve


