##################################################
FROM node:10.12.0

WORKDIR /usr/src/app

RUN npm install nodemon -g
RUN npm i -g @adonisjs/cli


##################################################
#RUN apt-get update && apt-get install -y vim
#COPY . .
#COPY package*.json ./
#RUN npm install

##A porta já está esposta no docker-compose.yml
#EXPOSE 3333

#O comando ja eh rodado no docker-compose.yml
#CMD [ "nodemon", "server.js" ]
##################################################

