version: '3.2'

services:
  mysql-db-sia:
    image: mysql:5.7
    container_name: mysql-db-sia
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    links:
      - mysql-db-sia
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql-db-sia

  backend-sia:
    build: .
    container_name: backend-sia
    restart: always
    ports:
       - 3333:3333
    volumes:
       - ./:/usr/src/app
    command: nodemon server.js
    links:
        - mysql-db-sia
    depends_on:
      - mysql-db-sia

volumes:
  data:


